const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),path=require('path'),assert=require('assert');
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.exposeFunction('recordShot',async name=>{await page.screenshot({path:'test-results/adventure-'+name+'.png'});});
await page.goto(process.env.GAME_URL||'file:///'+path.resolve(__dirname,'../prototypes/m1/index.html').replaceAll('\\','/'));await page.waitForFunction(()=>window.Magnet3D);await page.screenshot({path:'test-results/adventure-start.png'});await page.keyboard.press('Enter');await page.keyboard.down('KeyD');await page.keyboard.down('Space');await page.waitForTimeout(450);await page.keyboard.up('KeyD');await page.keyboard.up('Space');assert((await page.evaluate(()=>Magnet3D.snapshot())).count>0);await page.screenshot({path:'test-results/adventure-small.png'});
const result=await page.evaluate(async(digital)=>{
 const g=Magnet3D;g.reset();const trail=[],missed=[];
 function tick(x,z,frames=1){for(let i=0;i<frames;i++)g.step({x:digital?Math.sign(x):x,z:digital?Math.sign(z):z,attract:true});}
 function go(x,z,limit=Math.max(1600,Math.ceil(Math.hypot(x-g.position.x,z-g.position.z)/5*120)+400)){for(let i=0;i<limit;i++){let s=g.snapshot(),dx=x-s.position[0],dz=z-s.position[2];if(Math.hypot(dx,dz)<.65||s.state==='result')return true;let ax=dx-s.velocity[0]*.12,az=dz-s.velocity[2]*.12,n=Math.max(1,Math.hypot(ax,az));tick(ax/n,az/n);}return false;}
 function seek(region,limit){const failures=new Set();for(let j=0;j<limit&&g.snapshot().state==='play';j++){const s=g.snapshot();const target=g.objects.filter(o=>o.region===region&&!o.collected&&!o.goal&&!failures.has(o.id)&&o.need<=s.power).sort((a,b)=>Math.hypot(a.pos.x-s.position[0],a.pos.z-s.position[2])-Math.hypot(b.pos.x-s.position[0],b.pos.z-s.position[2]))[0];if(!target)break;let x=target.pos.x,z=target.pos.z;if(region===0&&s.position[1]<2&&x<5&&Math.abs(z)<3){failures.add(target.id);continue;}if(!go(x,z))failures.add(target.id);tick(0,0,45);if(!target.collected)failures.add(target.id);if(s.power>=g.objects.find(o=>o.region===region&&o.goal).need)break;}missed.push({region,failures:[...failures]});}
 seek(0,40);go(4,0);go(9,0);go(16,0);trail.push({label:'table and ramp',...g.snapshot()});
 // Broad floor sweep avoids cutting through the original bench footprint.
 for(let lap=0;lap<2&&g.snapshot().power<1.8;lap++)for(let i=0;i<24&&g.snapshot().power<1.8;i++){let a=i*Math.PI/12;go(Math.cos(a)*19,Math.sin(a)*17);}
 seek(0,60);trail.push({label:'workshop pile',...g.snapshot()});g.draw(0);let running=state;state='paused';await window.recordShot('workshop');state=running;
 go(0,7);go(0,4);tick(0,-1,240);trail.push({label:'workbench milestone',...g.snapshot()});
 for(let region=1;region<regions.length;region++){
  if(g.snapshot().stage<region)break;
  const start=[0,35,104,222,424,665,1045,1555,2140][region];go(start,0);seek(region,150);const target=g.objects.find(o=>o.region===region&&o.goal);trail.push({label:'region '+region+' before goal',...g.snapshot()});g.draw(0);const running=state;state='paused';await window.recordShot('district-'+region);state=running;go(target.pos.x,target.pos.z);tick(0,0,180);trail.push({label:'region '+region+' milestone',...g.snapshot()});
 }
 g.draw(0);return {trail,missed,parts:g.pile.parts.map(a=>({id:a.item.id,p:a.position.toArray(),actual:a.item.mesh.position.toArray(),scale:a.item.mesh.scale.toArray()}))};
},Boolean(process.env.DIGITAL));if(result.trail.at(-1).state!=='result')console.error(JSON.stringify({trail:result.trail,missed:result.missed},null,2));await page.screenshot({path:'test-results/adventure-end.png'});assert.equal(errors.length,0);assert.equal(result.trail.at(-1).state,'result','all district milestones');for(const s of result.trail)assert.equal(s.coreRadius,.32);for(const a of result.parts){assert.deepEqual(a.scale,[1,1,1]);assert.deepEqual(a.p,a.actual);}await page.keyboard.press('Enter');const late=await page.evaluate(()=>{const g=Magnet3D;const count=g.snapshot().count;let maxMs=0;for(let i=0;i<7200;i++){let t=performance.now();g.step({x:Math.sin(i/350),z:Math.cos(i/470),attract:false});maxMs=Math.max(maxMs,performance.now()-t);if(i%600===0&&(!g.snapshot().position.every(Number.isFinite)||g.snapshot().coreRadius!==.32))throw Error('late-game invalid');}g.draw(0);return{startCount:count,final:g.snapshot(),maxStepMs:maxMs};});const frames=await page.evaluate(()=>new Promise(resolve=>{let a=[],last=performance.now();function tick(t){a.push(t-last);last=t;if(a.length===121){a.shift();resolve({mean:a.reduce((x,y)=>x+y)/120,max:Math.max(...a),calls:Magnet3D.renderer.info.render.calls});}else requestAnimationFrame(tick);}requestAnimationFrame(tick);}));console.log(JSON.stringify({result,late,frames,errors},null,2));await page.screenshot({path:'test-results/adventure-roaming.png'});await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
