// Set PLAYWRIGHT_MODULE to an installed playwright path; game itself has no dependencies.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.GAME_URL||'file:///'+path.resolve(__dirname,'../prototypes/m1/delivery-2d.html').replaceAll('\\','/'));await page.screenshot({path:'test-results/start.png'});await page.keyboard.press('Enter');await page.keyboard.down('KeyD');await page.keyboard.down('Space');await page.waitForTimeout(1400);await page.keyboard.up('KeyD');await page.waitForTimeout(1600);await page.keyboard.up('Space');await page.screenshot({path:'test-results/assembly.png'});let collected=await page.evaluate(()=>Magnet.snapshot());assert(collected.attached>1,'normal keyboard collection');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>Magnet.snapshot().state),'paused');await page.keyboard.press('Enter');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.equal(await page.evaluate(()=>Magnet.snapshot().state),'paused');await page.keyboard.press('Enter');await page.keyboard.press('KeyR');assert.equal(await page.evaluate(()=>Magnet.snapshot().attached),1);
// Complete wide route using movement/field inputs, no placement of bodies.
const route=await page.evaluate(()=>{Magnet.reset();function input(x,y,mode,n){for(let i=0;i<n;i++)Magnet.step({x,y,mode})}function go(x,y,max=12000){for(let i=0;i<max;i++){let p=Magnet.snapshot().core,dx=x-p.x,dy=y-p.y;if(Math.hypot(dx,dy)<7)return true;Magnet.step({x:Math.abs(dx)>5?Math.sign(dx):0,y:Math.abs(dy)>5?Math.sign(dy):0,mode:0})}return false}let points=[];function record(label){points.push({label,...Magnet.snapshot()})}go(255,550);input(0,0,0,120);record('near block');input(0,0,1,720);record('capture');go(400,585);record('detour entry');go(740,585);record('detour clear');go(995,370);record('bay');input(0,0,0,600);record('rest');Magnet.draw();return points});await page.screenshot({path:'test-results/route.png'});
if(route.at(-1).state!=='result')console.error(JSON.stringify(route,null,2));assert.equal(route.at(-1).state,'result','complete heavy-block route');
const compact=await page.evaluate(()=>{Magnet.reset();function input(x,y,mode,n){for(let i=0;i<n;i++)Magnet.step({x,y,mode})}function go(x,y){for(let i=0;i<16000&&Magnet.snapshot().state==='play';i++){let p=Magnet.snapshot().core,dx=x-p.x,dy=y-p.y;if(Math.hypot(dx,dy)<7)return;Magnet.step({x:Math.abs(dx)>5?Math.sign(dx):0,y:Math.abs(dy)>5?Math.sign(dy):0,mode:0})}}input(1,0,1,168);input(0,0,1,192);go(425,580);go(740,580);go(1000,350);input(0,0,0,600);Magnet.draw();return Magnet.snapshot()});assert.equal(compact.state,'result','compact load route');await page.screenshot({path:'test-results/compact-result.png'});
const narrow=await page.evaluate(()=>{Magnet.reset();function go(x,y){for(let i=0;i<4000;i++){let p=Magnet.snapshot().core,dx=x-p.x,dy=y-p.y;if(Math.hypot(dx,dy)<5)return;Magnet.step({x:Math.abs(dx)>3?Math.sign(dx):0,y:Math.abs(dy)>3?Math.sign(dy):0,mode:0})}}go(180,382);go(480,382);go(650,382);go(795,255);for(let i=0;i<240;i++)Magnet.step({x:0,y:0,mode:1});Magnet.draw();return Magnet.snapshot()});assert(narrow.core.x>600&&narrow.anchorSeen,'narrow route to anchor');await page.screenshot({path:'test-results/anchor.png'});
await page.keyboard.press('KeyR');await page.keyboard.down('Space');const render=await page.evaluate(()=>new Promise(resolve=>{let times=[],last=performance.now();function f(now){times.push(now-last);last=now;if(times.length===180)resolve({mean:times.slice(1).reduce((a,b)=>a+b,0)/179,max:Math.max(...times.slice(1)),userAgent:navigator.userAgent,resolution:[innerWidth,innerHeight]});else requestAnimationFrame(f)}requestAnimationFrame(f)}));await page.keyboard.up('Space');assert.equal(errors.length,0);console.log(JSON.stringify({browser:browser.version(),collected,route,compact,narrow,render,errors},null,2));await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
