const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),path=require('path'),assert=require('assert');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.SHOWROOM_URL||'file:///'+path.resolve(__dirname,'../prototypes/m1/showroom.html').replaceAll('\\','/'));await page.waitForFunction(()=>window.SalvageShowroom);await page.click('#turntable');
 const models=await page.evaluate(()=>Object.keys(defs).map(kind=>{const a=model(kind),b=model(kind),box=new T.Box3().setFromObject(a);if(!box.min.toArray().concat(box.max.toArray()).every(Number.isFinite))throw Error('Invalid bounds '+kind);return{kind,parts:a.userData.rawParts,draws:a.children.length,triangles:a.userData.triangles,cached:a.children[0].geometry===b.children[0].geometry};}));
 assert.equal(models.length,45);for(const m of models){assert(m.cached,m.kind+' cached geometry');assert(m.draws<m.parts,m.kind+' batching');}
 for(const kind of ['car','van','tower','bench','bolt','bike','container','forklift','can']){await page.selectOption('#object',kind);await page.screenshot({path:'test-results/detail-'+kind+'.png'});}
 await page.selectOption('#object','car');await page.check('#crushed');await page.screenshot({path:'test-results/detail-car-crushed.png'});assert(await page.evaluate(()=>SalvageShowroom.display.userData.crushed));await page.selectOption('#object','bolt');assert(await page.locator('#crushed').isDisabled());assert.equal(await page.locator('#crushed').isChecked(),false);
 await page.selectOption('#object','car');await page.click('#next');assert.equal(await page.locator('#object').inputValue(),'van');await page.click('#previous');assert.equal(await page.locator('#object').inputValue(),'car');
 const before=await page.evaluate(()=>camera.position.toArray());await page.mouse.move(900,400);await page.mouse.down();await page.mouse.move(1100,480,{steps:10});await page.mouse.up();await page.waitForTimeout(100);assert.notDeepEqual(await page.evaluate(()=>camera.position.toArray()),before);
 await page.setViewportSize({width:600,height:850});await page.screenshot({path:'test-results/detail-mobile-gallery.png'});
 await page.click('header a');await page.waitForFunction(()=>window.Magnet3D);const count=await page.evaluate(()=>{Magnet3D.reset();for(let i=0;i<240;i++)Magnet3D.step({x:1,z:0,attract:true});return Magnet3D.snapshot().count;});assert(count>0);await page.click('#inspectModels');await page.waitForFunction(()=>window.SalvageShowroom);await page.click('header a');await page.waitForFunction(()=>window.Magnet3D);assert(await page.locator('#continue').isVisible());await page.evaluate(()=>{document.getElementById('continue').click();Magnet3D.pause();});assert((await page.evaluate(()=>Magnet3D.snapshot().count))>=count);
 assert.deepEqual(errors,[]);console.log(JSON.stringify({models,galleryRoundTripPreserved:true,errors},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
