const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),path=require('path'),assert=require('assert');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.GAME_URL||'file:///'+path.resolve(__dirname,'../prototypes/m1/index.html').replaceAll('\\','/'));await page.waitForFunction(()=>window.Magnet3D);
 const report=await page.evaluate(()=>{
  Magnet3D.reset();const original=[];originalLayout((kind)=>original.push(kind));const prefix=objects.slice(0,original.length).map(o=>o.kind);if(JSON.stringify(prefix)!==JSON.stringify(original))throw Error('Legacy object IDs changed');
  for(const kind of ['bench','forklift','bus','sculpture'])collect(objects.find(o=>o.kind===kind));save();const legacy=JSON.parse(JSON.stringify(saveData));legacy.stage=3;delete legacy.found;legacy.free=legacy.free.filter(o=>o.id<490);saveData=legacy;restore();const migrated={stage,count:pile.parts.length,goals:[...goals],total:objects.length};
  const ids=pile.parts.map(a=>a.item.id),before=p.toArray(),locked=travelTo(5),after=p.toArray();travelTo(0);const back=p.x;travelTo(4);const rail=p.x,retained=ids.every(id=>pile.parts.some(a=>a.item.id===id));
  collect(objects.find(o=>o.kind==='locomotive'));p.x=900;collect(objects.find(o=>o.kind==='crane'));repel();const ejected=objects.filter(o=>!o.collected&&o.cool>0).map(o=>o.pos.x);save();restore();const harbor=stage;
  reset();for(const o of objects.filter(o=>['tool','drill','toolbox'].includes(o.kind)).slice(0,10))collect(o);const notesBefore=FieldNotes.snapshot();repel();for(const o of objects.filter(o=>!o.collected&&o.cool>0))collect(o);const notesAfter=FieldNotes.snapshot();save();restore();const notesRestored=FieldNotes.snapshot();state='paused';
  return{original:original.length,migrated,locked,before,after,back,rail,retained,ejected,harbor,notesBefore,notesAfter,notesRestored};
 });assert.equal(report.original,490);assert.equal(report.migrated.stage,4);assert.equal(report.migrated.total,1297);assert.equal(report.locked,false);assert.deepEqual(report.before,report.after);assert.equal(report.back,17);assert.equal(report.rail,438);assert(report.retained);assert(report.ejected.every(x=>x>650));assert.equal(report.harbor,5);assert.equal(report.notesBefore.completed,1);assert.deepEqual(report.notesBefore,report.notesAfter);assert.deepEqual(report.notesAfter,report.notesRestored);
 await page.click('#fieldNotes');assert(await page.locator('#fieldPanel').isVisible());await page.screenshot({path:'test-results/expansion-notes.png'});await page.click('#fieldNotes');await page.click('#inspectModels');await page.waitForFunction(()=>window.SalvageShowroom);await page.click('#turntable');for(const kind of ['excavator','tankcar','locomotive','tugboat','crane','freighter','drill','toolbox','vending','trafficlight']){await page.selectOption('#object',kind);await page.screenshot({path:'test-results/expansion-'+kind+'.png'});}assert.deepEqual(errors,[]);console.log(JSON.stringify({...report,errors},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
