const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),path=require('path'),assert=require('assert');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto(process.env.GAME_URL||'file:///'+path.resolve(__dirname,'../prototypes/m1/index.html').replaceAll('\\','/'));await page.waitForFunction(()=>window.Magnet3D);
 const quietDiscovery=await page.evaluate(()=>{reset();toast.textContent='';toastTimer=0;collect(objects.find(o=>o.kind==='bolt'));return{toast:toast.textContent,timer:toastTimer,arrow:scene.children.some(o=>o.type==='ArrowHelper')};});assert.deepEqual(quietDiscovery,{toast:'',timer:0,arrow:false});
 const migration=await page.evaluate(()=>{reset();const old=[];dockLayout(kind=>old.push(kind));if(old.some((kind,i)=>objects[i].kind!==kind))throw Error('Pre-airfield IDs changed');for(const kind of ['bench','forklift','bus','sculpture','locomotive','freighter'])collect(objects.find(o=>o.kind===kind));save();const legacy=JSON.parse(JSON.stringify(saveData));delete legacy.packing;legacy.stage=5;legacy.free=legacy.free.filter(o=>o.id<790);saveData=legacy;restore();return{stage,old:old.length,total:objects.length,core:core.scale.x,highSupported:GraphicsPass.supported,art:WorldArt.stats};});assert.equal(migration.stage,6);assert.equal(migration.old,790);assert.equal(migration.total,1116);assert.equal(migration.core,.32);
 for(const [name,x,z,yawValue] of [['city',290,0,Math.PI/2],['docks',855,80,.8],['airfield',1270,0,Math.PI/2],['launch',1810,0,Math.PI/2]]){await page.evaluate(({x,z,yawValue})=>{reset();stage=x<410?3:x<1020?5:x<1530?6:7;goals=new Set(regions.slice(0,stage).map(r=>r.goal));state='play';p.set(x,.35,z);toastTimer=0;compass.textContent=regions[stage].hint;yaw=yawValue;pitch=.3;Magnet3D.draw(0);state='paused';}, {x,z,yawValue});await page.screenshot({path:'test-results/graphics-'+name+'.png'});}
 const pixels=await page.evaluate(()=>{Magnet3D.draw(0);const c=document.createElement('canvas');c.width=64;c.height=64;const ctx=c.getContext('2d');ctx.drawImage(renderer.domElement,0,0,64,64);const bytes=ctx.getImageData(0,0,64,64).data;let min=255,max=0;for(let i=0;i<bytes.length;i+=4){min=Math.min(min,bytes[i]);max=Math.max(max,bytes[i]);}return{min,max,size:GraphicsPass.size};});assert(pixels.max-pixels.min>40,'scene must not be blank');assert.deepEqual(pixels.size,[1440,900]);
 await page.setViewportSize({width:1000,height:700});await page.evaluate(()=>Magnet3D.draw(0));assert.deepEqual(await page.evaluate(()=>GraphicsPass.size),[1000,700]);await page.click('#optionsToggle');await page.selectOption('#quality','low');await page.check('#reduced');await page.click('#optionsToggle');await page.screenshot({path:'test-results/graphics-low.png'});assert.equal(await page.evaluate(()=>renderer.shadowMap.enabled),false);await page.click('#optionsToggle');await page.selectOption('#quality','high');await page.click('#optionsToggle');await page.evaluate(()=>Magnet3D.draw(0));assert.equal(await page.evaluate(()=>renderer.shadowMap.enabled),true);
 await page.click('#inspectModels');await page.waitForFunction(()=>window.SalvageShowroom);await page.setViewportSize({width:1440,height:900});await page.click('#turntable');for(const kind of ['suitcase','baggagecart','fueltruck','propplane','controltower','airliner','satellite','rover','radar','launchtruck','rocket']){await page.selectOption('#object',kind);await page.screenshot({path:'test-results/graphics-model-'+kind+'.png'});await page.check('#crushed');await page.screenshot({path:'test-results/graphics-crushed-'+kind+'.png'});await page.uncheck('#crushed');}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({migration,pixels,errors},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
