// Run: node tests/physics.cjs. Executes the exact embedded game simulation.
const fs=require('fs'),vm=require('vm'),assert=require('assert'),{performance}=require('perf_hooks');
const html=fs.readFileSync(require('path').join(__dirname,'../prototypes/m1/delivery-2d.html'),'utf8');
function game(){const elements={},context=new Proxy({}, {get:()=>()=>{}});const document={createElement:()=>({}),querySelector:()=>({appendChild(){}}),getElementById:id=>elements[id]||(elements[id]={getContext:()=>context,hidden:true,value:'hold',checked:false,addEventListener(){},blur(){}}),addEventListener(){}};const sandbox={document,window:{addEventListener(){}},localStorage:{getItem(){throw Error('blocked')},setItem(){throw Error('blocked')},removeItem(){}},performance,requestAnimationFrame(){},console};vm.createContext(sandbox);vm.runInContext(html.match(/<script>([\s\S]*)<\/script>/)[1],sandbox);return sandbox.window.Magnet}
const results=[];function test(name,fn){const t=performance.now();fn();results.push({name,passed:true,ms:Math.round(performance.now()-t)})}
function run(g,seconds,input){for(let i=0;i<Math.round(seconds*120);i++)g.step(typeof input==='function'?input(i):input||{x:0,y:0,mode:0})}
test('offline reset, 28 physical pieces, 24 compact units',()=>{let g=game();g.reset();assert.equal(g.snapshot().parts,28);assert.equal(g.bodies.filter(b=>b.mass===1).length,24);for(let i=0;i<100;i++)g.reset();assert.equal(g.snapshot().parts,28);assert.equal(g.snapshot().elapsed,0)});
test('merge preserves world geometry and linear/angular momentum',()=>{let g=game();g.reset();let a=g.player,b=g.bodies[1];a.vel={x:15,y:3};a.omega=.4;b.vel={x:-5,y:4};b.omega=-.2;let before=[...a.parts.map(s=>g.world(a,s)),...b.parts.map(s=>g.world(b,s))];let P={x:a.mass*a.vel.x+b.mass*b.vel.x,y:a.mass*a.vel.y+b.mass*b.vel.y},L=a.inertia*a.omega+b.inertia*b.omega+a.mass*(a.p.x*a.vel.y-a.p.y*a.vel.x)+b.mass*(b.p.x*b.vel.y-b.p.y*b.vel.x);g.merge(a,b);assert(Math.abs(a.mass*a.vel.x-P.x)<1e-9);assert(Math.abs(a.mass*a.vel.y-P.y)<1e-9);assert(Math.abs(a.inertia*a.omega+a.mass*(a.p.x*a.vel.y-a.p.y*a.vel.x)-L)<1e-6);for(let s of before){let after=g.world(a,a.parts.find(q=>q.id===s.id));assert(Math.hypot(s.p.x-after.p.x,s.p.y-after.p.y)<1e-8)}});
test('heavy-body reaction and static anchor pull in normal layout',()=>{let g=game();g.reset();g.player.p={x:255,y:550};let block=g.bodies.find(b=>b.mass===20),px=g.player.p.x,bx=block.p.x;run(g,.2,{x:0,y:0,mode:1});assert(g.player.p.x>px);assert(block.p.x<bx);assert(g.player.p.x-px>bx-block.p.x);g.reset();g.player.p={x:795,y:250};run(g,1,{x:0,y:0,mode:1});assert(g.snapshot().core.y<245);assert(g.snapshot().anchorSeen)});
test('repel keeps all colliders and prevents immediate recapture',()=>{let g=game();g.reset();let b=g.bodies[1];b.p={x:164,y:340};g.merge(g.player,b);run(g,.1,{x:0,y:0,mode:-1});assert.equal(g.snapshot().attached,1);assert.equal(g.snapshot().parts,28);run(g,.1,{x:0,y:0,mode:1});assert.equal(g.snapshot().attached,1)});
test('pipe silhouette blocks 52px shortcut; repel recovers jam',()=>{let g=game();g.reset();let pipe=g.bodies.find(b=>b.parts[0].kind==='pipe');g.player.p={x:485,y:382};pipe.p={x:512,y:382};pipe.a=0;g.merge(g.player,pipe);run(g,4,{x:1,y:0,mode:0});assert(g.snapshot().core.x<550);run(g,1,{x:-1,y:0,mode:-1});assert.equal(g.snapshot().attached,1);run(g,1,{x:0,y:0,mode:0});assert(g.snapshot().core.x<510)});
test('one-second delivery, no duplicate scoring, restart result',()=>{let g=game();g.reset();g.player.p={x:935,y:330};let block=g.bodies.find(b=>b.mass===20);block.p={x:1015,y:330};run(g,.9);assert.equal(g.snapshot().score,0);run(g,.2);assert.equal(g.snapshot().state,'result');assert.equal(g.snapshot().score,200);run(g,2);assert.equal(g.snapshot().score,200);g.reset();assert.equal(g.snapshot().score,0)});
test('render-rate traces at 30/60/120 FPS stay within 2%',()=>{let traces=[];for(let fps of [30,60,120]){let g=game();g.reset();let accumulator=0;for(let f=0;f<fps*10;f++){accumulator+=1/fps;while(accumulator>=1/120-1e-12){g.step({x:0,y:1,mode:0});accumulator-=1/120}}traces.push(g.snapshot())}for(let trace of traces)assert(Math.hypot(trace.core.x-traces[0].core.x,trace.core.y-traces[0].core.y)<.01);results.push({traces:traces.map(t=>({position:t.core,elapsed:t.elapsed,score:t.score}))})});
if(!process.env.SKIP_STRESS)test('ten-minute 40-piece alternating-field stress, finite and bounded',()=>{let g=game();g.reset();g.stress();let samples=[];for(let i=0;i<72000;i++){let t=performance.now();g.step({x:Math.sin(i/360),y:Math.cos(i/480),mode:Math.floor(i/120)%2?1:-1});samples.push(performance.now()-t);if(i%1200===0){assert.equal(g.snapshot().parts,40);for(let b of g.bodies){assert(Number.isFinite(b.p.x+b.p.y+b.a+b.vel.x+b.vel.y));assert(b.p.x>-100&&b.p.x<1220&&b.p.y>-100&&b.p.y<780)}}}samples.sort((a,b)=>a-b);results.push({stress:{steps:72000,simulatedSeconds:600,parts:g.snapshot().parts,contacts:g.snapshot().maxContacts,meanMs:samples.reduce((a,b)=>a+b,0)/samples.length,p95Ms:samples[Math.floor(samples.length*.95)],maxMs:samples.at(-1)}})});
console.log(JSON.stringify(results,null,2));
