'use strict';
scene.clear();scene.background=new T.Color('#172b33');scene.fog=new T.Fog('#172b33',22,55);
scene.add(new T.HemisphereLight(0xdceffc,0x414545,2));sun.position.set(-5,9,6);sun.intensity=3.5;sun.shadow.camera.left=-9;sun.shadow.camera.right=9;sun.shadow.camera.top=9;sun.shadow.camera.bottom=-9;sun.shadow.camera.far=35;sun.shadow.camera.updateProjectionMatrix();scene.add(sun);
const rimLight=new T.DirectionalLight(0x87bbd2,2.2);rimLight.position.set(6,5,-6);scene.add(rimLight);
const stageMesh=new T.Mesh(new T.CylinderGeometry(4.1,4.15,.14,96),new T.MeshStandardMaterial({color:'#293d43',roughness:.88,metalness:.1}));stageMesh.position.y=-.1;stageMesh.receiveShadow=true;scene.add(stageMesh);
const ground=new T.Mesh(new T.PlaneGeometry(200,200),new T.MeshStandardMaterial({color:'#172b33',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.19;ground.receiveShadow=true;scene.add(ground);
const detailNotes={bolt:'Hexagonal head, machined socket, thread rings and a steel washer.',can:'Rolled steel rims, enamel lid, wire bail and a printed industrial label.',tool:'Forged jaws, rounded handle, recessed shank and maker’s stamp.',pipe:'Flanged ends, dark bores, hex fasteners and rolled collars.',wheel:'Rubber tire, laced metal spokes, hub and polished rim.',stool:'Pressed seat, fasteners, splayed legs, rubber feet and a foot ring.',locker:'Inset door, louvers, hinges, handle, lock and numbered badge.',bench:'Individual timber planks, steel bracing, drawers and bolted legs.',barrel:'Rolled ribs, sealed lid, hex bung and a hazard label.',cart:'Open tubular frame, hand grips, loading tray and detailed casters.',bike:'Triangulated frame, laced wheels, crank, pedals, saddle and handlebars.',skip:'Open bin, reinforced ribs, rolled edges and loose scrap inside.',forklift:'Seat, steering wheel, hydraulic mast, canopy, beacon and forks.',hydrant:'Bolted caps, flange, valve nut and dangling chain links.',sign:'Rounded sign plate, punched pole, fasteners and direction lettering.',car:'Tapered cabin, seating, windscreen, mirrors, door seams and wheel hardware.',van:'Enclosed cargo body, cab windows, sliding-door seams and a roof rack.',bus:'Individual windows, destination boards, body trim and roof equipment.',truck:'Separate cab and cargo body, shutter door, rivets and fleet signage.',tram:'Transit glazing, route plates, roof electrical gear and steel trim.',kiosk:'Open serving counter, newspaper stacks, posters and a framed canopy.',container:'Corrugated shell, corner castings, twin doors, locking rods and freight markings.',tower:'Steel tank, banded seams, conical roof, ladder, cage and cross-bracing.',sculpture:'Tapered steel lattice, diagonal bracing, baseplates and a crown of rings.'};
Object.assign(detailNotes,{toolbox:'Rounded steel shell, lid, carrying handle, clasps and a maker’s badge.',drill:'Battery pack, molded grip, motor vents, chuck and steel drill bit.',vending:'Inset product display, selection buttons, pickup slot and printed header.',trafficlight:'Suspended signal head, colored lenses, protective rims and a tubular support.',excavator:'Tracked chassis, glazed cab, hydraulic rams, articulated boom and toothed bucket.',tankcar:'Banded tank, fill hatch, ladder, rail wheelsets and couplers.',locomotive:'Glazed cab, engine ventilation, roof fans, handrails, bogies and couplers.',tugboat:'Tapered hull, wheelhouse, deck rails, radar mast and rubber fenders.',crane:'Braced gantry, cab, lattice boom, counterweight, lifting cable and hook.',freighter:'Tapered hull, corrugated deck cargo, bridge windows, railings and radar mast.'});
Object.assign(detailNotes,{suitcase:'Molded shell, protective ribs, carrying handle, wheels and a luggage label.',baggagecart:'Loaded luggage trailer with railings, casters and a tow coupling.',fueltruck:'Tanker body, banded fuel vessel, access ladder and aviation fuel markings.',propplane:'Propeller, fuselage, cabin glazing, wings, tailplane and landing gear.',controltower:'Glazed observation deck, reinforced shaft, radar bar and airport signage.',airliner:'Swept wings, tapered fuselage, cockpit glazing, cabin windows, engine fans and landing gear.'});
Object.assign(detailNotes,{satellite:'Faceted instrument bus, solar arrays, antenna mast, thrusters and gold thermal panels.',rover:'Six-wheel articulated explorer with a camera mast, dish, suspension arms and equipment deck.',radar:'Tilting parabolic reflector, receiver horn, rotating yoke, access platform and braced pedestal.',launchtruck:'Massive tracked transporter with lifting deck, machinery housings, railings and control cabins.',rocket:'Multi-stage launch vehicle with engine bells, interstage bands, fins, service markings and payload fairing.'});
const kinds=Object.keys(defs);$('object').innerHTML=kinds.map(k=>'<option value="'+k+'">'+defs[k].label+'</option>').join('');
let display=null,angle=.65,elevation=.27,distance=10,rotating=true,dragging=false,lastTime=0;
function showModel(kind){
 angle=['car','van','bus','truck','tram','airliner','propplane'].includes(kind)?2.35:.65;
 if(display)scene.remove(display);const supported=!!CrushWorkshop.profiles[kind];$('crushed').disabled=!supported;if(!supported)$('crushed').checked=false;
 display=$('crushed').checked?CrushWorkshop.build(kind):model(kind);const b=new T.Box3().setFromObject(display),size=b.getSize(new T.Vector3()),center=b.getCenter(new T.Vector3()),scale=5/Math.max(...size.toArray());display.scale.setScalar(scale);display.position.set(-center.x*scale,-b.min.y*scale,-center.z*scale);scene.add(display);
 $('object').value=kind;$('name').textContent=defs[kind].label.toLowerCase().replace(/(^|\s)\S/g,s=>s.toUpperCase());$('number').textContent=String(kinds.indexOf(kind)+1).padStart(2,'0')+' / '+kinds.length;$('description').textContent=detailNotes[kind]||'Industrial salvage with modeled structural parts, surface wear and hardware. Collect it as your pile grows.';
}
$('object').onchange=()=>showModel($('object').value);$('crushed').onchange=()=>showModel($('object').value);$('turntable').onclick=()=>{rotating=!rotating;$('turntable').textContent=rotating?'Pause rotation':'Rotate model';};
function advance(n){showModel(kinds[(kinds.indexOf($('object').value)+n+kinds.length)%kinds.length]);}$('previous').onclick=()=>advance(-1);$('next').onclick=()=>advance(1);
$('world').onpointerdown=e=>{dragging=true;$('world').setPointerCapture(e.pointerId);};$('world').onpointerup=()=>dragging=false;$('world').onpointermove=e=>{if(dragging){angle-=e.movementX*.007;elevation=T.MathUtils.clamp(elevation+e.movementY*.005,-.04,1.1);}};$('world').addEventListener('wheel',e=>{e.preventDefault();distance=T.MathUtils.clamp(distance+e.deltaY*.006,5.5,17);},{passive:false});
function resizeShowroom(){renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}window.addEventListener('resize',resizeShowroom);resizeShowroom();
showModel(new URLSearchParams(location.search).get('object') in defs?new URLSearchParams(location.search).get('object'):'car');
function showroomFrame(now){const dt=Math.min(.05,(now-lastTime)/1000||0);lastTime=now;if(rotating&&!dragging)angle+=dt*.16;const target=new T.Vector3(0,1.6,0);camera.position.set(Math.sin(angle)*distance*Math.cos(elevation),1.6+Math.sin(elevation)*distance,Math.cos(angle)*distance*Math.cos(elevation));camera.lookAt(target);camera.setViewOffset(innerWidth,innerHeight,-innerWidth*(innerWidth>700?.12:0),0,innerWidth,innerHeight);renderer.render(scene,camera);requestAnimationFrame(showroomFrame);}requestAnimationFrame(showroomFrame);
window.SalvageShowroom={show:showModel,get display(){return display;},get kinds(){return kinds;}};
